version: '3.8'

services:
  backend:
    image: todo-backend:v1
    container_name: todo-backend
    ports:
      - "8080:8080"
    networks:
      - todo-net

  frontend:
    image: todo-frontend:v1
    container_name: todo-frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - todo-net

networks:
  todo-net:
    driver: bridge
