spring.application.name=todo-backend
# Pour activer la console H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuration JPA + H2
spring.datasource.url=jdbc:h2:mem:todo-db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
